version: 2.1
orbs:
  architect: giantswarm/architect@2.2.0

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push kube-bench-app chart to giantswarm-playground-catalog"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          context: architect
          chart: "kube-bench-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
