version: 2.1
orbs:
  architect: giantswarm/architect@0.5.2

e2eTest: &e2eTest
  machine: true
  working_directory: /home/circleci/.go_workspace/src/github.com/giantswarm/kube-bench-app
  steps:
    - checkout

    - attach_workspace:
        at: .

    - run:
        name: Get kubectl binary
        command: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl

    - run:
        name: Get e2ectl binary
        command: |
          wget -q $(curl -sS https://api.github.com/repos/giantswarm/e2ectl/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          chmod +x ./e2ectl
    - run:
        name: Init cluster
        command: |
          ./e2ectl cluster create
          cp $(./e2ectl kubeconfig path) ${E2E_TEST_DIR}/kubeconfig

    - run:
        name: Run test
        command: |
          docker run --rm --network host \
            -v $(pwd)/${E2E_TEST_DIR}:/e2e \
            -v $(pwd):/go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
            -e E2E_TARBALL_URL=https://giantswarm.github.io/default-test-catalog/kube-bench-app-$(./architect project version).tgz \
            -e E2E_KUBECONFIG=/e2e/kubeconfig \
            -e CIRCLE_SHA1=${CIRCLE_SHA1} \
            -w /go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
            golang:1 go test -v -tags k8srequired ./${E2E_TEST_DIR}/

    - run:
        name: Export logs
        command: |
          ./e2ectl logs export --logs-dir=kind/logs
        when: always

    - store_artifacts:
        path: kind/logs
        destination: logs

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Get architect binary
          command: |
            wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
            chmod +x ./architect
            ./architect version
      - run: ./architect build

      - persist_to_workspace:
          root: .
          paths:
            - ./architect

  e2eTestBasic:
    environment:
      E2E_TEST_DIR: "integration/test/basic"
      E2E_TEST_NAME: "basic"
    <<: *e2eTest

workflows:
  version: 2
  build_e2e:
    jobs:
      - build

      - architect/push-to-app-catalog:
          name: "package-and-push-kube-bench-app-chart"
          app_catalog: "giantswarm-incubator-catalog"
          app_catalog_test: "giantswarm-incubator-test-catalog"
          chart: "kube-bench-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - e2eTestBasic:
          requires:
            - build
            - package-and-push-kube-bench-app-chart
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
