apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.name  . }}
  namespace: {{ tpl .Values.namespace  . }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      version: {{ .Values.version }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.version }}
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Values.name }}
                  version: {{ .Values.version }}
              topologyKey: kubernetes.io/hostname
            weight: 100
      volumes:
      - name: {{ .Values.name }}-configmap
        configMap:
          name: {{ tpl .Values.name  . }}
          items:
          - key: config.yml
            path: config.yml
      serviceAccountName: {{ tpl .Values.name  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
        - daemon
        - --config.dirs=/var/run/{{ .Values.name }}/configmap/
        - --config.files=config
        volumeMounts:
        - name: {{ .Values.name }}-configmap
          mountPath: /var/run/{{ .Values.name }}/configmap/
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 100m
            memory: 220Mi
      # imagePullSecrets:
      # - name: {{ tpl .Values.resource.pullSecret.name . }}
