apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ tpl .Values.namespace  . }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535 
  runAsUser:
    rule: RunAsAny
  # runAsGroup:
  #   rule: MustRunAs
  #   ranges:
  #     - min: 1
  #       max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostIPC: false
  hostPID: true
