name: Update kube-bench version

on: repository_dispatch

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.tag }}
      - name: Create tag file
        run: >
          python3 -c "with open('./helm/kube-bench-app/image_tag.yaml', 'w') as f: f.write('${{ github.event.client_payload.tag }}\n')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[Automation] Update kube-bench version to ${{ github.event.client_payload.tag }}"
          branch-suffix: short-commit-hash
